{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kustom-controller.fullname" . }}-metrics
  labels:
    {{- include "kustom-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kustom-controller.selectorLabels" . | nindent 4 }}
{{- end }}